/*  Message-number definitions derived from "ELWCHT.MSG"  */

#define CHTKEY      1
#define CHTMS1      3
#define CHTMS2      4
#define ACTMS1      5
#define ACTMS2      6
#define WELCOME     7
#define EXIT        8
#define GLOHELP     9
#define SYSHELP    10
#define SENT       11
#define ACTSENT    12
#define GETNAME    13
#define SORRY      14
#define REDO       15
#define INCHT      16
#define PROMPT     17
